name: appname 
attributes:
  ORGANIZATIONNAME: tmsae
options:
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: com.tmsae
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: '14.0'
  fileGroups:
    - Sources
    - Supporting Files
configs:
  Development-Debug: debug
  Development-Release: release
  AppStore-Debug: debug
  AppStore-Release: release
configFiles:
  Development-Debug: Supporting Files/Environment/Debug.xcconfig
  Development-Release: Supporting Files/Environment/Release.xcconfig
  AppStore-Debug: Supporting Files/Environment/Debug.xcconfig
  AppStore-Release: Supporting Files/Environment/Release.xcconfig
scheme: 
  mydano: 
    build:
      targets:
        mydano: all
    archive:
      config: AppStore Release
targets:
  appname:
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
    scheme:
      configVariants:
        - Development 
        - AppStore
    type: application
    platform: iOS
    devices: [iPhone, iPad]
    entitilements: 
      path: Supporting Files/appname.entitlements
    deploymentTarget: '14.0'
    settings: 
      base:
        INFOPLIST_FILE: Supporting Files/Info.plist
        FRAMEWORK_SEARCH_PATHS: [$(inherited), $(PROJECT_DIR), $(SRCROOT)]
        LIBRARY_SEARCH_PATHS: [$(inherited)]
        DEVELOPMENT_TEAM: **********
        CODE_SIGN_STYLE: Manual
        ENABLE_BITCODE: false 
        TARGETED_DEVICE_FAMILY: 1
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      configs: 
        Development-Debug:
          PRODUCT_BUNDLE_IDENTIFIER: "com.tmsae.appname"
          CODE_SIGN_IDENTITY: iPhone Developer 
          PROVISIONING_PROFILE_SPECIFIER: match Development com.tmsae.appname
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-function-bodies=150 -Xfrontend -warn-long-expression-type-checking=150
          DEBUG_INFORMATION_FORMAT: dwarf
        Development-Release:
          PRODUCT_BUNDLE_IDENTIFIER: "com.tmsae.appname"
          CODE_SIGN_IDENTITY: iPhone Developer 
          PROVISIONING_PROFILE_SPECIFIER: match Development com.tmsae.appname
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        AppStore: 
          PRODUCT_BUNDLE_IDENTIFIER: "com.tmsae.appname"
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.tmsae.appname
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    sources:
      - Sources
      - path: 'Supporting Files'
        type: group
      - path: 'Resources'
        type: group
    postBuildScripts:
      - path: BuildScripts/GoogleServiceInfoCopy.sh
        name: GoogleService-Info Copy
      - path: BuildScripts/FirebaseCrashlytics.sh
        name: Firebase Crashlytics 
        inputFiles: 
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
      - path: BuildScripts/SwiftGen.sh
        name: SwiftGen 